BaseExperiment: &defaults
    dataset_name: adni
    seed: 42
    root_dir: !ENV ${FASTMRI_ROOT}
    batch_size: 64
    use_fg_mask: False

    singlecoil_train1_ds:
        csv_file: ./datasets/singlecoil_adni_train1.csv
        fg_dir: singlecoil_train1_foreground
        full: True
        slices:
            min: 64
            max: -64
        patch:
            patch_ny: 320
            offset_y: 0
    singlecoil_val1_ds:
        csv_file: ./datasets/singlecoil_adni_val1.csv
        fg_dir: singlecoil_val1_foreground
        full: True
        slices:
            min: 64
            max: -64
        patch:
            patch_ny: 320
            offset_y: 0
    singlecoil_test_ds:
        csv_file: ./datasets/singlecoil_adni_test.csv
        fg_dir: singlecoil_test_foreground
        full: True
        slices:
            min: 64
            max: -64
        patch:
            patch_ny: 320
            offset_y: 0

    accelerations: [8]
    center_fractions: [0.04]
    # accelerations: [2, 4, 6, 8]
    # center_fractions: [0.16, 0.08, 0.06, 0.04]
    # accelerations: [2, 4, 6, 8] 
    # center_fractions: [0.16, 0.08, 0.06, 0.04]
    num_smaps: 2