BaseExperiment: &defaults
    dataset_name: knee
    seed: 42
    root_dir: !ENV ${FASTMRI_ROOT}
    batch_size: 8
    use_fg_mask: False
    singlecoil_train_ds:
        csv_file: ./datasets/singlecoil_knee_train0.csv
        fg_dir: singlecoil_train_foreground
        full: False
        slices:
            min: 8
        patch:
            patch_ny: 128
            offset_y: 0
            remove_feos: True
    singlecoil_val_ds:
        csv_file: ./datasets/singlecoil_knee_val0.csv
        fg_dir: singlecoil_val_foreground
        full: False
        slices:
            min: 12
            max: 25
        patch:
            patch_ny: 320
            offset_y: 0
            remove_feos: True
    singlecoil_test_ds:
        csv_file: ./datasets/fastmri_singlecoil_knee_test.csv
        fg_dir: singlecoil_val_foreground
    data_filter:
        acquisition:
            - CORPD_FBK
    # acc offset
    accelerations: [4, 8, 16, 32, 64] 
    center_fractions: [0.16, 0.08, 0.04, 0.02, 0.01]
    num_smaps: 2