BaseExperiment: &defaults
    seed: 42
    #root_dir: !ENV ${FASTMRI_ROOT}
    # root_dir: /home/wenqi/Data/FastMRI/
    root_dir: /labspace/data/public/fastmri
    batch_size: 8
    use_fg_mask: False
    singlecoil_train_ds:
        csv_file: ./datasets/fastmri_singlecoil_knee_train.csv
        fg_dir: singlecoil_train_foreground
        full: False
        slices:
            min: 8
        patch:
            patch_ny: 128
            offset_y: 0
            remove_feos: True
    singlecoil_val_ds:
        csv_file: ./datasets/fastmri_singlecoil_knee_val.csv
        fg_dir: singlecoil_val_foreground
        full: False
        slices:
            min: 12
            max: 25
        patch:
            patch_ny: 320
            offset_y: 0
            remove_feos: True
    singlecoil_test_ds:
        csv_file: ./datasets/fastmri_singlecoil_knee_val.csv
        fg_dir: singlecoil_val_foreground
    multicoil_train_ds:
        csv_file: ./datasets/fastmri_multicoil_knee_train.csv
        sens_dir: multicoil_train_espirit
        fg_dir: multicoil_train_foreground
        full: False
        slices:
            min: 8
        patch:
            patch_ny: 96
            offset_y: 0
            remove_feos: True
    multicoil_val_ds:
        csv_file: ./datasets/fastmri_multicoil_knee_val.csv
        sens_dir: multicoil_val_espirit
        fg_dir: multicoil_val_foreground
        full: False
        slices:
            min: 12
            max: 25
        patch:
            patch_ny: 320
            offset_y: 0
            remove_feos: True
    multicoil_test_ds:
        csv_file: ./datasets/fastmri_multicoil_knee_val.csv
        sens_dir: multicoil_val_espirit
        fg_dir: multicoil_val_foreground
    data_filter:
        acquisition:
            - CORPD_FBK
    accelerations:
        - 4
    center_fractions:
        - 0.08
    num_smaps: 2