BaseExperiment: &defaults
    dataset_name: adni
    seed: 42
    root_dir: !ENV ${FASTMRI_ROOT}
    batch_size: 8
    use_fg_mask: False
    singlecoil_train_ds:
        csv_file: ./datasets/singlecoil_adni_train0.csv
        # csv_file: ./datasets/singlecoil_adni_overfit.csv
        fg_dir: singlecoil_train_foreground
        full: False
        slices:
            min: 8
        patch:
            patch_ny: 128
            offset_y: 0
            remove_feos: False
    singlecoil_val_ds:
        csv_file: ./datasets/singlecoil_adni_val0.csv
        # csv_file: ./datasets/singlecoil_adni_overfit.csv
        fg_dir: singlecoil_val_foreground
        full: False
        slices:
            min: 12
            max: 25
        patch:
            patch_ny: 320
            offset_y: 0
            remove_feos: False
    singlecoil_test_ds:
        csv_file: ./datasets/singlecoil_adni_test.csv
        fg_dir: singlecoil_val_foreground
        full: False
        slices:
            min: 12
            max: 25
        patch:
            patch_ny: 320
            offset_y: 0
            remove_feos: False
    accelerations: [2, 4, 6, 8]
    center_fractions: [0.16, 0.08, 0.06, 0.04]
    num_smaps: 2